### ISSUE TITLE
chaincode directory

### ISSUE THREAD

**Issue by blockchaindul** [IBM-Blockchain-Archive/marbles#21] opened 2016-07-07 09:43 UTC
I run takes marvels chaincode local download, it did not find the directory connection ...

Under inde part of the js code, I'd like to run the js chaincode local, download the code in relation to the local server time-consuming just to be running on the local server. 

How can I change non-zip and unzip and local chaincode call in the following?

```
        zip_url: 'https://github.com/ibm-blockchain/marbles-chaincode/archive/master.zip', 
        unzip_dir: 'marbles-chaincode-master / part2_v1.0.0', 
        git_url: 'https://github.com /ibm-blockchain/marbles-chaincode/part2_v1.0.0 '
```

**Comment by masterDev1985** [comment] 2016-07-07 13:50
I believe this is a duplicate of your issue [here](https://github.com/IBM-Blockchain/ibm-blockchain-js/issues/18).  My recommendation is the same:

Investigate the new SDK that is coming from the Hyperledger fabric team. This SDK will support deploying chaincode from a local folder. [Click here](https://github.com/hyperledger/fabric/tree/master/sdk/node#readme) to see the SDK.

We are in the process of updating this demo to support the new SDK.  If you check back later, you'll be able to refer to this demo as an example of how to use the new SDK.

**Closed as completed** 2016-07-07 17:01 UTC
Labels: question, wontfix
