### ISSUE TITLE
hfc-key-store folder not in the expected location

### ISSUE THREAD

**Issue by tgmerritt** [IBM-Blockchain-Archive/marbles#186] opened 2018-01-04 23:45 UTC
I found when following the install_chaincode.js step and error as follows:

`Error: ENOENT: no such file or directory, open '/Users/i851546/.hfc-key-store/cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec-priv'`

But I'm using the fabric-samples local repo - which means the correct path is:

/Users/i851546/**fabric-samples/fabcar/hfc-key-store/**

For my purposes, I created a symlink in my home folder so that .hfc-key-store points to the correct folder.  This allowed the JS to execute fully.

I believe that at some point in the Marbles app, it should be looking for the fabric-samples repo.  But it doesn't appear to do that.

**Comment by dshuffma-ibm** [comment] 2018-01-05 00:54
this issue is caused by the same one outline in https://github.com/IBM-Blockchain/marbles/issues/175.  going to close this version. thanks for the report though.  

for anyone else reading this, do the same as @tgmerritt.

**Closed as completed by dshuffma-ibm** 2018-01-05 00:54 UTC

**Comment by skerbz** [comment] 2018-01-16 10:05
username:scripts username$ node install_chaincode.js
info: Loaded config file /Users/username/go/src/hyperledger/fabric/examples/chaincode/go/chaincode_example02/marbles/config/marbles_local.json
info: Loaded creds file /Users/username/go/src/hyperledger/fabric/examples/chaincode/go/chaincode_example02/marbles/config/blockchain_creds_local.json
---------------------------------------
info: Lets install some chaincode - marbles v4
---------------------------------------
info: First we enroll
info: [fcw] Going to enroll with admin cert!  peer_urls=[grpc://localhost:7051], channel_id=mychannel, uuid=marbles-Docker Compose Network-mychannel-fabric-peer-org1, orderer_url=grpc://localhost:7050, msp_id=Org1MSP
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/username/.hfc-key-store/cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec-priv'
username:scripts username$

**Comment by vinayakkulkarni** [comment] 2018-03-05 09:58
```bash
Vinayaks-MacBook-Pro:scripts work$ mkdir /Users/work/.hfc-key-store/
Vinayaks-MacBook-Pro:scripts work$ ln -s /Users/work/Development/blockchain/fabric-samples/fabcar/hfc-key-store/ /Users/work/.hfc-key-store/
```

Symlinking does the trick for now.
